name: Build Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            artifact_name: kontrola_tymu_macos
            output_file: kontrola_tymu
          - os: windows-latest
            artifact_name: kontrola_tymu_windows
            output_file: kontrola_tymu.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Prepare
        uses: actions/checkout@v4

      - name: LLVM and Clang
        if: runner.os == 'Windows'
        run: choco install llvm -y

      - name: Scala CLI
        uses: VirtusLab/scala-cli-setup@main

      - name: Build
        run: scala-cli --power package kontrola_tymu.scala --native --native-mode release-full -o -f ${{ matrix.output_file }}

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.output_file }}
          if-no-files-found: error