name: Build Executables

# Spustí se automaticky při nahrání nového kódu na větev main, 
# nebo to můžeš spustit ručně z GitHub rozhraní.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Vytvoříme dvě paralelní sestavení - pro Mac a pro Windows
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            artifact_name: kontrola_tymu_macos
            output_file: kontrola_tymu
          - os: windows-latest
            artifact_name: kontrola_tymu_windows
            output_file: kontrola_tymu.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Stazeni repozitare
        uses: actions/checkout@v4

      - name: Instalace LLVM a Clang pro Windows
        if: runner.os == 'Windows'
        run: choco install llvm -y

      - name: Nastaveni Scala CLI
        uses: VirtusLab/scala-cli-setup@main

      - name: Kompilace nativni binarky
        run: scala-cli --power package kontrola_tymu.scala --native --native-mode release-full -o ${{ matrix.output_file }}

      - name: Nahrani vysledku (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.output_file }}
          if-no-files-found: error